#!/bin/bash

if [ ! $1 ]; then
    echo "arg 1 hnId must be supplied"
    exit
fi

echo "FYI: PWD is $PWD"

if [ ! ${PWD##*/} = "whoshiring" ]; then
    echo "Wrong PWD $PWD"
    exit
fi

MAX_P=9

echo "Grabbing HN message $1 at URLs https://news.ycombinator.com/item?id=$1/p=1..$MAX_P"

mkdir -p files/temp/$1
mkdir -p files/backup/$1

rm files/temp/$1/*.*
touch files/temp/$1/hn.js

for ((x=1;x<=MAX_P;x++)); do
      echo "x=$x"
      curl  "https://news.ycombinator.com/item?id=$1&p=$x" > files/temp/$1/$x.html
      ./iframify files/temp/$1/$x.html
done

rm -r files/backup/$1
cp -r files/$1 files/backup/$1

rm -r files/$1
cp -r files/temp/$1 files/$1

ls -al files/$1

exit #-----------------------------------------------------

if [ ! -f temp/$1.tmp ]; then
    echo "Download target temp/$1.tmp not found after curl."
    exit
fi

if diff -q temp/$1.tmp files/$1.html; then
  echo "$1.html has NOT changed"
  exit
else
  echo "$1.html HAS changed"
  epoch=`date +%s`
  echo "epoch is $epoch"
  mkdir -p files/backup
  cp files/$1.html files/backup/$1.$epoch.html
  mv temp/$1.tmp files/$1.html
  git add files/$1.html
  git commit -m "Grab new $1 page"
  git push
fi

echo "Bye-bye"